[2025-01-18T21:22:31.006+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-18T21:22:31.015+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2025-01-18T21:22:31.019+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2025-01-18T21:22:31.020+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-18T21:22:31.058+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2023-02-10 00:00:00+00:00
[2025-01-18T21:22:31.063+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=298) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-18T21:22:31.064+0000] {standard_task_runner.py:72} INFO - Started process 307 to run task
[2025-01-18T21:22:31.064+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2023-02-10T00:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpgjzp67bf']
[2025-01-18T21:22:31.066+0000] {standard_task_runner.py:105} INFO - Job 109: Subtask extract
[2025-01-18T21:22:31.091+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [running]> on host e9a1739d3128
[2025-01-18T21:22:31.158+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-10T00:00:00+00:00'
[2025-01-18T21:22:31.159+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-18T21:22:31.176+0000] {logging_mixin.py:190} INFO - 2023-02
[2025-01-18T21:22:31.316+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: 404 Client Error: Not Found for url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2023-02
[2025-01-18T21:22:31.316+0000] {logging_mixin.py:190} INFO - None
[2025-01-18T21:22:31.316+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-18T21:22:31.321+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-18T21:22:31.321+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2023-02-10T00:00:00+00:00, execution_date=20230210T000000, start_date=20250118T212231, end_date=20250118T212231
[2025-01-18T21:22:31.358+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-18T21:22:31.363+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-19T20:06:20.822+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T20:06:20.831+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2025-01-19T20:06:20.836+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2025-01-19T20:06:20.836+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T20:06:20.848+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2023-02-10 00:00:00+00:00
[2025-01-19T20:06:20.852+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T20:06:20.853+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2023-02-10T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpup67b2hp']
[2025-01-19T20:06:20.855+0000] {standard_task_runner.py:72} INFO - Started process 121 to run task
[2025-01-19T20:06:20.855+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask extract
[2025-01-19T20:06:20.886+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [running]> on host 659dab735c6e
[2025-01-19T20:06:20.937+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-10T00:00:00+00:00'
[2025-01-19T20:06:20.938+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T20:06:20.950+0000] {logging_mixin.py:190} INFO - 2023-02
[2025-01-19T20:06:21.087+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: 404 Client Error: Not Found for url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2023-02
[2025-01-19T20:06:21.089+0000] {logging_mixin.py:190} INFO - -----------------
[2025-01-19T20:06:21.090+0000] {logging_mixin.py:190} INFO - None
[2025-01-19T20:06:21.090+0000] {logging_mixin.py:190} INFO - ['Cnaes']
[2025-01-19T20:06:21.092+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 96, in extract
    for file in files:
                ^^^^^
TypeError: 'NoneType' object is not iterable
[2025-01-19T20:06:21.102+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2023-02-10T00:00:00+00:00, execution_date=20230210T000000, start_date=20250119T200620, end_date=20250119T200621
[2025-01-19T20:06:21.124+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-19T20:06:21.124+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task extract ('NoneType' object is not iterable; 121)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 96, in extract
    for file in files:
                ^^^^^
TypeError: 'NoneType' object is not iterable
[2025-01-19T20:06:21.149+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-19T20:06:21.160+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-19T20:06:21.163+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-19T22:19:13.910+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T22:19:13.921+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2025-01-19T22:19:13.925+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2025-01-19T22:19:13.926+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T22:19:13.935+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2023-02-10 00:00:00+00:00
[2025-01-19T22:19:13.939+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=439) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T22:19:13.940+0000] {standard_task_runner.py:72} INFO - Started process 447 to run task
[2025-01-19T22:19:13.940+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2023-02-10T00:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpld88q297']
[2025-01-19T22:19:13.941+0000] {standard_task_runner.py:105} INFO - Job 137: Subtask extract
[2025-01-19T22:19:13.971+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [running]> on host 659dab735c6e
[2025-01-19T22:19:14.018+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-10T00:00:00+00:00'
[2025-01-19T22:19:14.019+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T22:19:14.031+0000] {logging_mixin.py:190} INFO - 2023-02
[2025-01-19T22:19:14.168+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: 404 Client Error: Not Found for url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2023-02
[2025-01-19T22:19:14.168+0000] {logging_mixin.py:190} INFO - -----------------
[2025-01-19T22:19:14.169+0000] {logging_mixin.py:190} INFO - None
[2025-01-19T22:19:14.169+0000] {logging_mixin.py:190} INFO - ['Cnaes', 'Empresas', 'Estabelecimentos', 'Motivos', 'Municipios', 'Naturezas', 'Paises', 'Qualificacoes', 'Simples', 'Socios']
[2025-01-19T22:19:14.170+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 100, in extract
    for file in files:
                ^^^^^
TypeError: 'NoneType' object is not iterable
[2025-01-19T22:19:14.179+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2023-02-10T00:00:00+00:00, execution_date=20230210T000000, start_date=20250119T221913, end_date=20250119T221914
[2025-01-19T22:19:14.190+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-19T22:19:14.210+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 137 for task extract ('NoneType' object is not iterable; 447)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 100, in extract
    for file in files:
                ^^^^^
TypeError: 'NoneType' object is not iterable
[2025-01-19T22:19:14.234+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-19T22:19:14.257+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-19T22:19:14.260+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-24T19:01:05.224+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T19:01:05.236+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2025-01-24T19:01:05.243+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2025-01-24T19:01:05.244+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T19:01:05.255+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2023-02-10 00:00:00+00:00
[2025-01-24T19:01:05.259+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=736) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T19:01:05.260+0000] {standard_task_runner.py:72} INFO - Started process 768 to run task
[2025-01-24T19:01:05.261+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2023-02-10T00:00:00+00:00', '--job-id', '403', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpjg1nvqct']
[2025-01-24T19:01:05.263+0000] {standard_task_runner.py:105} INFO - Job 403: Subtask extract
[2025-01-24T19:01:05.294+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-02-10T00:00:00+00:00 [running]> on host ee70781c29c7
[2025-01-24T19:01:05.349+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-10T00:00:00+00:00'
[2025-01-24T19:01:05.350+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T19:01:05.364+0000] {logging_mixin.py:190} INFO - Data formatada: 2023-02
[2025-01-24T19:01:05.496+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: 404 Client Error: Not Found for url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2023-02
[2025-01-24T19:01:05.496+0000] {logging_mixin.py:190} INFO - Arquivos encontrados: []
[2025-01-24T19:01:05.497+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-24T19:01:05.502+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T19:01:05.503+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2023-02-10T00:00:00+00:00, execution_date=20230210T000000, start_date=20250124T190105, end_date=20250124T190105
[2025-01-24T19:01:05.514+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T19:01:05.532+0000] {taskinstance.py:3895} INFO - 10 downstream tasks scheduled from follow-on schedule check
[2025-01-24T19:01:05.534+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
