[2025-01-18T21:22:26.837+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-18T21:22:26.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2025-01-18T21:22:26.855+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2025-01-18T21:22:26.855+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-18T21:22:26.893+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2022-06-10 00:00:00+00:00
[2025-01-18T21:22:26.898+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=262) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-18T21:22:26.900+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2025-01-18T21:22:26.899+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2022-06-10T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmp9sqq1dyy']
[2025-01-18T21:22:26.901+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask extract
[2025-01-18T21:22:26.933+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [running]> on host e9a1739d3128
[2025-01-18T21:22:26.990+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2022-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-06-10T00:00:00+00:00'
[2025-01-18T21:22:26.991+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-18T21:22:27.004+0000] {logging_mixin.py:190} INFO - 2022-06
[2025-01-18T21:22:27.143+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: 404 Client Error: Not Found for url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2022-06
[2025-01-18T21:22:27.144+0000] {logging_mixin.py:190} INFO - None
[2025-01-18T21:22:27.144+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-18T21:22:27.151+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-18T21:22:27.151+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2022-06-10T00:00:00+00:00, execution_date=20220610T000000, start_date=20250118T212226, end_date=20250118T212227
[2025-01-18T21:22:27.194+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-18T21:22:27.206+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-18T21:22:27.208+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-19T20:06:20.081+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T20:06:20.091+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2025-01-19T20:06:20.096+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2025-01-19T20:06:20.097+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T20:06:20.106+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2022-06-10 00:00:00+00:00
[2025-01-19T20:06:20.110+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T20:06:20.111+0000] {standard_task_runner.py:72} INFO - Started process 99 to run task
[2025-01-19T20:06:20.111+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2022-06-10T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpdqtj_97q']
[2025-01-19T20:06:20.113+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask extract
[2025-01-19T20:06:20.146+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [running]> on host 659dab735c6e
[2025-01-19T20:06:20.201+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2022-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-06-10T00:00:00+00:00'
[2025-01-19T20:06:20.202+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T20:06:20.215+0000] {logging_mixin.py:190} INFO - 2022-06
[2025-01-19T20:06:21.440+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: 404 Client Error: Not Found for url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2022-06
[2025-01-19T20:06:21.441+0000] {logging_mixin.py:190} INFO - -----------------
[2025-01-19T20:06:21.441+0000] {logging_mixin.py:190} INFO - None
[2025-01-19T20:06:21.441+0000] {logging_mixin.py:190} INFO - ['Cnaes']
[2025-01-19T20:06:21.442+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 96, in extract
    for file in files:
                ^^^^^
TypeError: 'NoneType' object is not iterable
[2025-01-19T20:06:21.454+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2022-06-10T00:00:00+00:00, execution_date=20220610T000000, start_date=20250119T200620, end_date=20250119T200621
[2025-01-19T20:06:21.463+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-19T20:06:21.464+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task extract ('NoneType' object is not iterable; 99)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 96, in extract
    for file in files:
                ^^^^^
TypeError: 'NoneType' object is not iterable
[2025-01-19T20:06:21.488+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-19T20:06:21.499+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-19T20:06:21.502+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-19T22:19:12.974+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T22:19:12.984+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2025-01-19T22:19:12.989+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2025-01-19T22:19:12.990+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T22:19:13.000+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2022-06-10 00:00:00+00:00
[2025-01-19T22:19:13.004+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=413) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T22:19:13.005+0000] {standard_task_runner.py:72} INFO - Started process 425 to run task
[2025-01-19T22:19:13.005+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2022-06-10T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpjmfxdjh2']
[2025-01-19T22:19:13.007+0000] {standard_task_runner.py:105} INFO - Job 129: Subtask extract
[2025-01-19T22:19:13.036+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [running]> on host 659dab735c6e
[2025-01-19T22:19:13.088+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2022-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-06-10T00:00:00+00:00'
[2025-01-19T22:19:13.089+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T22:19:13.102+0000] {logging_mixin.py:190} INFO - 2022-06
[2025-01-19T22:19:13.242+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: 404 Client Error: Not Found for url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2022-06
[2025-01-19T22:19:13.243+0000] {logging_mixin.py:190} INFO - -----------------
[2025-01-19T22:19:13.243+0000] {logging_mixin.py:190} INFO - None
[2025-01-19T22:19:13.243+0000] {logging_mixin.py:190} INFO - ['Cnaes', 'Empresas', 'Estabelecimentos', 'Motivos', 'Municipios', 'Naturezas', 'Paises', 'Qualificacoes', 'Simples', 'Socios']
[2025-01-19T22:19:13.244+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 100, in extract
    for file in files:
                ^^^^^
TypeError: 'NoneType' object is not iterable
[2025-01-19T22:19:13.256+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2022-06-10T00:00:00+00:00, execution_date=20220610T000000, start_date=20250119T221912, end_date=20250119T221913
[2025-01-19T22:19:13.266+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-19T22:19:13.266+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 129 for task extract ('NoneType' object is not iterable; 425)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 100, in extract
    for file in files:
                ^^^^^
TypeError: 'NoneType' object is not iterable
[2025-01-19T22:19:13.299+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-19T22:19:13.303+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-24T19:01:04.123+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T19:01:04.132+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2025-01-24T19:01:04.137+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2025-01-24T19:01:04.138+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T19:01:04.202+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2022-06-10 00:00:00+00:00
[2025-01-24T19:01:04.205+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=695) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T19:01:04.206+0000] {standard_task_runner.py:72} INFO - Started process 710 to run task
[2025-01-24T19:01:04.206+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2022-06-10T00:00:00+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpxdjqfdc8']
[2025-01-24T19:01:04.207+0000] {standard_task_runner.py:105} INFO - Job 386: Subtask extract
[2025-01-24T19:01:04.236+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2022-06-10T00:00:00+00:00 [running]> on host ee70781c29c7
[2025-01-24T19:01:04.300+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2022-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-06-10T00:00:00+00:00'
[2025-01-24T19:01:04.301+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T19:01:04.316+0000] {logging_mixin.py:190} INFO - Data formatada: 2022-06
[2025-01-24T19:01:04.448+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: 404 Client Error: Not Found for url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2022-06
[2025-01-24T19:01:04.449+0000] {logging_mixin.py:190} INFO - Arquivos encontrados: []
[2025-01-24T19:01:04.449+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-24T19:01:04.457+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T19:01:04.457+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2022-06-10T00:00:00+00:00, execution_date=20220610T000000, start_date=20250124T190104, end_date=20250124T190104
[2025-01-24T19:01:04.499+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T19:01:04.505+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
