[2025-01-24T21:04:49.814+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T21:04:49.824+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract_municipios manual__2025-01-24T20:59:53.324100+00:00 [queued]>
[2025-01-24T21:04:49.829+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract_municipios manual__2025-01-24T20:59:53.324100+00:00 [queued]>
[2025-01-24T21:04:49.830+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-01-24T21:04:49.883+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_municipios> on 2025-01-24 20:59:53.324100+00:00
[2025-01-24T21:04:49.887+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=810) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T21:04:49.888+0000] {standard_task_runner.py:72} INFO - Started process 831 to run task
[2025-01-24T21:04:49.889+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract_municipios', 'manual__2025-01-24T20:59:53.324100+00:00', '--job-id', '799', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpl3k_eefi']
[2025-01-24T21:04:49.891+0000] {standard_task_runner.py:105} INFO - Job 799: Subtask extract_municipios
[2025-01-24T21:04:49.922+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract_municipios manual__2025-01-24T20:59:53.324100+00:00 [running]> on host ee70781c29c7
[2025-01-24T21:04:49.974+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract_municipios' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T20:59:53.324100+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T20:59:53.324100+00:00'
[2025-01-24T21:04:49.975+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T21:04:49.987+0000] {logging_mixin.py:190} INFO - Data formatada: 2025-01
[2025-01-24T21:04:50.097+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: HTTPSConnectionPool(host='arquivos.receitafederal.gov.br', port=443): Max retries exceeded with url: /dados/cnpj/dados_abertos_cnpj/2025-01 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
[2025-01-24T21:04:50.097+0000] {logging_mixin.py:190} INFO - Arquivos encontrados: []
[2025-01-24T21:04:50.097+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-24T21:04:50.102+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T21:04:50.102+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract_municipios, run_id=manual__2025-01-24T20:59:53.324100+00:00, execution_date=20250124T205953, start_date=20250124T210449, end_date=20250124T210450
[2025-01-24T21:04:50.142+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T21:04:50.221+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T21:04:50.224+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
