[2025-01-24T22:28:37.610+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T22:28:37.619+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract_estabelecimentos manual__2025-01-24T21:15:51.387766+00:00 [queued]>
[2025-01-24T22:28:37.625+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract_estabelecimentos manual__2025-01-24T21:15:51.387766+00:00 [queued]>
[2025-01-24T22:28:37.625+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 5
[2025-01-24T22:28:37.653+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_estabelecimentos> on 2025-01-24 21:15:51.387766+00:00
[2025-01-24T22:28:37.657+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2230) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T22:28:37.658+0000] {standard_task_runner.py:72} INFO - Started process 2231 to run task
[2025-01-24T22:28:37.658+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract_estabelecimentos', 'manual__2025-01-24T21:15:51.387766+00:00', '--job-id', '860', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpcol0oup0']
[2025-01-24T22:28:37.660+0000] {standard_task_runner.py:105} INFO - Job 860: Subtask extract_estabelecimentos
[2025-01-24T22:28:37.686+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract_estabelecimentos manual__2025-01-24T21:15:51.387766+00:00 [running]> on host ee70781c29c7
[2025-01-24T22:28:37.738+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract_estabelecimentos' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T21:15:51.387766+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T21:15:51.387766+00:00'
[2025-01-24T22:28:37.739+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T22:28:37.754+0000] {logging_mixin.py:190} INFO - Data formatada: 2025-01
[2025-01-24T22:28:37.904+0000] {logging_mixin.py:190} INFO - Erro ao listar os arquivos: HTTPSConnectionPool(host='arquivos.receitafederal.gov.br', port=443): Max retries exceeded with url: /dados/cnpj/dados_abertos_cnpj/2025-01 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
[2025-01-24T22:28:38.131+0000] {logging_mixin.py:190} INFO - Arquivos encontrados: []
[2025-01-24T22:28:38.132+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-24T22:28:38.138+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T22:28:38.139+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract_estabelecimentos, run_id=manual__2025-01-24T21:15:51.387766+00:00, execution_date=20250124T211551, start_date=20250124T222837, end_date=20250124T222838
[2025-01-24T22:28:38.152+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T22:28:38.162+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T22:28:38.164+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
